# action.yml
name: 'Git Sync'
description: 'Sync two independent repositories'
inputs:
  args:  # id of input
    description: 'args'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.args }}